"""passed added created_warmup to track bad warm-up creation

Revision ID: 19bdcee24af4
Revises: 8d7d52522bfc
Create Date: 2021-02-19 01:30:33.012136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19bdcee24af4'
down_revision = '8d7d52522bfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('created_warmup', sa.Column('passed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('created_warmup', 'passed')
    # ### end Alembic commands ###
