"""table creation

Revision ID: 7b8bdbeba217
Revises: 
Create Date: 2021-02-08 12:25:19.686393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b8bdbeba217'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('move_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('warmup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warmup_name'), 'warmup', ['name'], unique=True)
    op.create_table('workout',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_name'), 'workout', ['name'], unique=True)
    op.create_table('roles_users',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'user_id')
    )
    op.create_table('warm_types',
    sa.Column('move_type_id', sa.Integer(), nullable=False),
    sa.Column('warm_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['move_type_id'], ['move_type.id'], ),
    sa.ForeignKeyConstraint(['warm_id'], ['warmup.id'], ),
    sa.PrimaryKeyConstraint('move_type_id', 'warm_id')
    )
    op.create_table('warm_work',
    sa.Column('warm_id', sa.Integer(), nullable=False),
    sa.Column('work_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['warm_id'], ['warmup.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['workout.id'], ),
    sa.PrimaryKeyConstraint('warm_id', 'work_id')
    )
    op.create_table('work_types',
    sa.Column('move_type_id', sa.Integer(), nullable=False),
    sa.Column('work_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['move_type_id'], ['move_type.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['workout.id'], ),
    sa.PrimaryKeyConstraint('move_type_id', 'work_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work_types')
    op.drop_table('warm_work')
    op.drop_table('warm_types')
    op.drop_table('roles_users')
    op.drop_index(op.f('ix_workout_name'), table_name='workout')
    op.drop_table('workout')
    op.drop_index(op.f('ix_warmup_name'), table_name='warmup')
    op.drop_table('warmup')
    op.drop_table('user')
    op.drop_table('role')
    op.drop_table('move_type')
    # ### end Alembic commands ###
