"""execution time added to created warmups

Revision ID: 8d7d52522bfc
Revises: 0c51e4d777f5
Create Date: 2021-02-17 14:38:59.522121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d7d52522bfc'
down_revision = '0c51e4d777f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('created_warmup', sa.Column('ex_time', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('created_warmup', 'ex_time')
    # ### end Alembic commands ###
