"""tracking created warm-ups

Revision ID: bf7604dc8e2c
Revises: 7b8bdbeba217
Create Date: 2021-02-08 13:12:32.533550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf7604dc8e2c'
down_revision = '7b8bdbeba217'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('created_warmup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_created_warmup_date'), 'created_warmup', ['date'], unique=False)
    op.create_table('create_warm',
    sa.Column('create_id', sa.Integer(), nullable=False),
    sa.Column('warm_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['create_id'], ['created_warmup.id'], ),
    sa.ForeignKeyConstraint(['warm_id'], ['warmup.id'], ),
    sa.PrimaryKeyConstraint('create_id', 'warm_id')
    )
    op.create_table('create_work',
    sa.Column('create_id', sa.Integer(), nullable=False),
    sa.Column('work_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['create_id'], ['created_warmup.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['workout.id'], ),
    sa.PrimaryKeyConstraint('create_id', 'work_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('create_work')
    op.drop_table('create_warm')
    op.drop_index(op.f('ix_created_warmup_date'), table_name='created_warmup')
    op.drop_table('created_warmup')
    # ### end Alembic commands ###
